service: aws-lambda

plugins:
  - serverless-offline

package:
  exclude:
    - node_modules/**
  individually: true
  minify: false

provider:
  name: aws
  region: ap-northeast-2
  runtime: nodejs18.x

functions:
  main:
    handler: dist/lambda.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'