# Node.js 이미지를 alpine을 사용하면서 image 크기를 줄임.
FROM node:18-alpine

# 전역으로 pm2 설치
RUN npm install -g pm2

# 작업 디렉토리 생성 및 설정
WORKDIR /app

# 패키지 파일을 복사하고 의존성 설치
COPY package*.json ./
RUN npm install

# 소스 코드 복사
COPY . .

# 빌드 및 실행
RUN npm run build

# 포트 노출
EXPOSE 3000

# 애플리케이션 실행
CMD ["pm2-runtime", "start", "ecosystem.config.js", "--only", "test", "--env", "production"]
